WebCL: Fix the build on Android 64-bits.
clGetKernelInfo() expects size_t parameters instead of cl_uint ones for
|param_value_size_ret|.

Since cl_uint is a typedef for uint32_t regardless of whether we're
building for 32 or 64 bits, the build was failing like this:

../../third_party/WebKit/Source/modules/webcl/WebCLProgram.cpp: In member function 'WTF::Vector<WTF::RefPtr<blink::WebCLKernel> > blink::WebCLProgram::createKernelsInProgram(blink::ExceptionState&)':
../../third_party/WebKit/Source/modules/webcl/WebCLProgram.cpp:262:100: error: cannot convert 'cl_uint* {aka unsigned int*}' to 'size_t* {aka long unsigned int*}' in argument passing
         err = clGetKernelInfo(kernelBuf[i], CL_KERNEL_FUNCTION_NAME, 0, nullptr, &bytesOfKernelName);
                                                                                                    ^

BUG=XWALK-3608