Revert 195102 "Merge 194914 "Web Animations: Fix leak of cleared..."
The merge was not clean, caused build failures.

[3371/3907] CXX obj\third_party\WebKit\Source\core\dom\webkit_unit_tests.DOMImplementationTest.obj
FAILED: ninja -t msvc -e environment.x86 -- "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\third_party\WebKit\Source\core\animation\webkit_unit_tests.AnimationStackTest.obj.rsp /c ..\..\third_party\WebKit\Source\core\animation\AnimationStackTest.cpp /Foobj\third_party\WebKit\Source\core\animation\webkit_unit_tests.AnimationStackTest.obj /Fdobj\third_party\WebKit\Source\web\webkit_unit_tests.cc.pdb 
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(123) : error C2065: 'ActiveInterpolationMap' : undeclared identifier
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(123) : error C2146: syntax error : missing ';' before identifier 'result'
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(123) : error C2065: 'result' : undeclared identifier
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(124) : error C2065: 'result' : undeclared identifier
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(124) : error C2228: left of '.size' must have class/struct/union
        type is 'unknown-type'
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(124) : error C2660: 'testing::internal::EqHelper<false>::Compare' : function does not take 3 arguments
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(124) : error C2512: 'testing::AssertionResult' : no appropriate default constructor available
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(125) : error C2065: 'result' : undeclared identifier
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(125) : error C2227: left of '->equals' must point to class/struct/union/generic type
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(125) : error C2512: 'testing::AssertionResult' : no appropriate default constructor available
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(128) : error C2065: 'result' : undeclared identifier
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(129) : error C2065: 'result' : undeclared identifier
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(129) : error C2228: left of '.size' must have class/struct/union
        type is 'unknown-type'
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(129) : error C2780: 'testing::AssertionResult testing::internal::EqHelper<true>::Compare(const char *,const char *,testing::internal::Secret *,T *)' : expects 4 arguments - 3 provided
        c:\b\build\slave\win_beta\build\src\testing\gtest\include\gtest\gtest.h(1558) : see declaration of 'testing::internal::EqHelper<true>::Compare'
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(129) : error C2780: 'testing::AssertionResult testing::internal::EqHelper<true>::Compare(const char *,const char *,const T1 &,const T2 &,EnableIf<!testing::internal::is_pointer<T2>::value>::type *)' : expects 5 arguments - 3 provided
        c:\b\build\slave\win_beta\build\src\testing\gtest\include\gtest\gtest.h(1540) : see declaration of 'testing::internal::EqHelper<true>::Compare'
c:\b\build\slave\win_beta\build\src\third_party\webkit\source\core\animation\animationstacktest.cpp(129) : error C2512: 'testing::AssertionResult' : no appropriate default constructor available
ninja: build stopped: subcommand failed.



> Merge 194914 "Web Animations: Fix leak of cleared SampledEffects"
> 
> > Web Animations: Fix leak of cleared SampledEffects
> > 
> > This patch fixes a leak where an AnimationStack would never let go of
> > SampledEffects. This leak was introduced when player collapsing was
> > removed in https://codereview.chromium.org/955303002.
> > 
> > BUG=481489
> > 
> > Review URL: https://codereview.chromium.org/1127483003
> 
> TBR=timloh@chromium.org
> 
> Review URL: https://codereview.chromium.org/1135723002

TBR=rune@opera.com

Review URL: https://codereview.chromium.org/1126053003

git-svn-id: svn://svn.chromium.org/blink/branches/chromium/2357@195115 bbb929c8-8fbe-4397-9dbb-9b2b20218538