export the entire HTMLResourcePreloader class in shared_library builds
After https://codereview.chromium.org/1112833004/ landed, libblink_web.so
fails to link in some configurations, giving this error:

obj/third_party/WebKit/Source/core/html/parser/blink_web.HTMLResourcePreloaderTest.o:HTMLResourcePreloaderTest.cpp:function blink::HTMLResourcePreloaderTest::test(blink::PreconnectTestCase): error: undefined reference to 'vtable for blink::HTMLResourcePreloader'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function

The blink::HTMLResourcePreloader vtable exists in lib/libwebcore_shared.so
but only as a local symbol, because I assume that the HTMLResourcePreloader
class has some un-exported virtual methods in these configuration.  So we
should be able to solve this by exporting the entire HTMLResourcePreloader
class.

Review URL: https://codereview.chromium.org/1266533002

git-svn-id: svn://svn.chromium.org/blink/trunk@199651 bbb929c8-8fbe-4397-9dbb-9b2b20218538